swagger: '2.0'

info:
  title: Storytime API
  description: An RESTful interface to the Storytime server, enabling all manner of choose-your-own-destiny games.
  termsOfService: http://www.ajegames.com/terms/
  contact:
    name: AJEGames Support
    url: http://www.ajegames.com/support/
    email: support@ajegames.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "1.0.0"
host: www.ajegames.com
basePath: /storytime/api/v1
schemes:
  - http
produces:
  - application/json

paths:
  /players:
    get:
      summary: Returns list of all active players
      description:
        Returns summary information for all players that are active in the system.
      operationId: getAllActivePlayers
      responses:
        '200':
          description: A list of players
          schema:
            type: array
            items:
              $ref: '#/definitions/Player'
  /players/{screenName}:
    get:
      summary: Returns player identified by screen name
      description:
        Returns player that matches the given screen name.
      operationId: getPlayer
      parameters:
        - name: screenName
          in: path
          type: string
          description: Alias for the player
          required: true
      responses:
        '200':
          description: A player
          schema:
            $ref: '#/definitions/Player'

definitions:
  Player:
    type: object
    required:
      - screenName
    properties:
      id:
        type: integer
        format: int64
      screenName:
        type: string
      emailAddress:
        type: string
      givenName:
        type: string
      sirName:
        type: string
