swagger: '2.0'

info:
  version: "0.1.0"
  title: StoryTime API

paths:
  /status:
    get:
      description: Gets information about the status of the StoryTime service.
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Status'

definitions:
  Status:
    type: object
    properties:
      salutation:
        type: string
      status:
        type: string
      version:
        type: string
